WITH
pos_changes as (
    SELECT *
        , LAG(SECURITY_HDIFF) OVER(PARTITION BY POSITION_HKEY ORDER BY RECORD_SOURCE) as PREV_HDIFF__POS
        , CASE 
            WHEN PREV_HDIFF__POS is null THEN true
            ELSE (SECURITY_HDIFF != PREV_HDIFF__POS) 
        END as CHANGE_IN_POS
    FROM {{ ref('STG_IB_OPEN_POSITIONS_SECURITY') }}
    QUALIFY CHANGE_IN_POS
)
SELECT * EXCLUDE(PREV_HDIFF__POS, CHANGE_IN_POS, CLIENT_ACCOUNT_CODE, POSITION_HKEY)
FROM pos_changes
ORDER BY SECURITY_SYMBOL, RECORD_SOURCE, CLIENT_ACCOUNT_CODE
