WITH
tx_changes as (
    SELECT *
        , LAG(SECURITY_HDIFF) OVER(PARTITION BY TRADE_HKEY ORDER BY RECORD_SOURCE) as PREV_HDIFF__TX
        , CASE 
            WHEN PREV_HDIFF__TX is null THEN true
            ELSE (SECURITY_HDIFF != PREV_HDIFF__TX) 
        END as CHANGE_IN_TX
    FROM {{ ref('STG_IB_TRADES_SECURITY') }}
    QUALIFY CHANGE_IN_TX
)
SELECT * EXCLUDE(PREV_HDIFF__TX, CHANGE_IN_TX)
FROM tx_changes
ORDER BY RECORD_SOURCE, TRANSACTION_ID
