SELECT
    ACCOUNT_ALIAS
    , SECURITY_SYMBOL
    , SECURITY_NAME
    , ASSET_CLASS


    , POSITION_VALUE_DATE
    , QUANTITY
    , SIDE
    , TRADING_CURRENCY

    -- values in trading currency (FX)
    , POSITION_VALUE    as MARKET_VALUE_FX
    , COST_BASIS_MONEY  as COST_BASIS_FX
    , POSITION_VALUE - COST_BASIS_MONEY as GAIN_FX
    , GAIN_PCT_FX

    -- values in base (at time of position value)
    , FX_RATE_TO_BASE
    , POSITION_VALUE_BASE    as MARKET_VALUE_BASE
    , COST_BASIS_BASE_APPROX as COST_BASIS_BASE
    , GAIN_BASE
    -- per share, FX
    , MARK_PRICE        as MARKET_PRICE_FX
    , COST_BASIS_PRICE  as COST_BASIS_PRICE_FX

    -- dates
    , POSITION_CHANGE_DATE
    , CALENDAR_DATE     as UPDATE_DATE

    -- codes
    , CLIENT_ACCOUNT_CODE
    , LISTING_EXCHANGE
    , SECURITY_CODE

FROM {{ ref('RPT_POSITIONS_DAILY_VALUES') }}
WHERE VALUE_IS_CURRENT
  and CALENDAR_DATE = CURRENT_DATE()
  and SIDE != 'Closed'
order by ACCOUNT_ALIAS, SECURITY_SYMBOL, CALENDAR_DATE, POSITION_VALUE_DATE
