SELECT
    SECURITY_SCD_HKEY
    , SECURITY_HKEY

    , LISTING_EXCHANGE
    , SECURITY_CODE
    , SECURITY_SYMBOL
    , SECURITY_NAME
    , CURRENCY_PRIMARY

    , EFFECTIVITY_DATE
    , REPORT_DATE

    , ASSET_CLASS
    , ISSUER
    , ISIN
    , CUSIP
    , CONID
    , PRINCIPAL_ADJUST_FACTOR

    , UNDERLYING_LISTING_EXCHANGE
    , UNDERLYING_SECURITY_CODE
    , UNDERLYING_SYMBOL
    , UNDERLYING_CONID
    , PUT_CALL
    , MULTIPLIER
    , STRIKE
    , EXPIRY

/*
    , BROKER_CODE
    , INGESTION_TS_UTC
    , HIST_LOAD_TS_UTC
    , RECORD_SOURCE

    , VALID_FROM
    , VALID_TO
    , IS_CURRENT
*/

FROM {{ ref('SCD_SECURITIES') }}
WHERE IS_CURRENT
