select 
    BROKER_CODE
    , CLIENT_ACCOUNT_CODE
    , ACCOUNT_ALIAS
    , LISTING_EXCHANGE
    , DIM_SECURITY_SYMBOL as SECURITY_SYMBOL
    , SECURITY_CODE
    , SECURITY_NAME

    , DIVIDEND_SETTLEMENT_DATE
    , MONTH
    , QUARTER
    , YEAR
    , YEAR_QUARTER

    , CURRENCY_PRIMARY
    , GROSS_DIVIDEND_RECIVED_IN_FX
    , TAX_PAID_IN_FX
    , COSTS_PAID_IN_FX
    , NET_CASH_RECIVED_IN_FX
    , AVG_FX_RATE_TO_BASE
    , GROSS_DIVIDEND_RECIVED_IN_BASE
    , TAX_PAID_IN_BASE
    , COSTS_PAID_IN_BASE
    , NET_CASH_RECIVED_IN_BASE

    , DIVIDEND_HKEY
    , PORTFOLIO_HKEY
    , POSITION_HKEY
    , POSITION_SCD_HKEY
    , SECURITY_HKEY
    , SECURITY_SCD_HKEY

from {{ ref('AGG_IB_DIVIDENDS') }}
