select
    TRANSACTION_HKEY
    , POSITION_HKEY
    , PORTFOLIO_HKEY
    , SECURITY_HKEY

    , TRANSACTION_ID
    , TRANSACTION_TYPE
    , TRANSACTION_TS

    , BROKER_CODE
    , CLIENT_ACCOUNT_CODE
    , ACCOUNT_ALIAS
    , LISTING_EXCHANGE
    , SECURITY_CODE
    , SECURITY_SYMBOL
    , SECURITY_NAME
    , ASSET_CLASS

    , EFFECTIVITY_DATE
    , BUY_SELL
    , QUANTITY
    , TX_MONEY_FX
    , CURRENCY_PRIMARY
    , FX_RATE_TO_BASE
    , TX_MONEY_BASE

    , COST_BASIS_FX as COST_BASIS_FX_CHANGE
    , OPEN_CLOSE_INDICATOR
    , NOTES_CODES

    , round(-TX_MONEY_FX / QUANTITY, 2) as TRADE_PRICE_FX
    , round(TX_MONEY_FX + COST_BASIS_FX_CHANGE, 2) as TRADE_GAIN_LOSS_FX

    , RECORD_SOURCE
    , INGESTION_TS_UTC
    , HIST_LOAD_TS_UTC

from {{ ref('REF_IB_POSITIONS_TRANSACTIONS') }}
order by ACCOUNT_ALIAS, SECURITY_SYMBOL, EFFECTIVITY_DATE, TRANSACTION_ID
